spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sekolah
    username: adminSekolah
    password: passwordSekolah
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db/migration
# Templates reloading during development
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    #    prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
#    prefix: ${project.basedir}/src/main/resources/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html
  devtools:
    livereload:
      enabled: true
    add-properties: true
  resources:
    static-locations: file:src/main/resources/static/
    #    static-locations: ${project.basedir}/src/main/resources/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
      location: ${java.io.tmpdir}

#We can use the httpOnly and secure flags to secure our session cookie:
#
#httpOnly: if true then browser script won't be able to access the cookie
#secure: if true then the cookie will be sent only over HTTPS connection
server:
  servlet:
    session:
      cookie:
        http-only: true
#        secure: true

# 1 days = 1 * 24 * 60 * 60
cookie:
  maxAge: 86400

#hendisantika/password
#admin/password